name: .NET 10 Avalonia Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    env:
      Solution_Name: GuitarNote.sln
      App_Project_Path: GuitarNote/GuitarNote.csproj

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 10 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build solution
      run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }}

    - name: Run unit tests
      run: dotnet test ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }}
